name: Greetings

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: 'Hi @${{ github.actor }} , thank you for submitting an issue!'
        pr-message: 'Hi @${{ github.actor }} , thanks for this PR! Your contributions are deeply valuable.'
